#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:20:00
#PBS -N app-splitshells
#PBS -V

rm -f finished

module load singularity 2> /dev/null
#if [ $ENV == "IUHPC" ]; then
#    module load matlab
#    module load singularity
#fi

echo "Running main.m"
#export MATLABPATH=$MATLABPATH:$SERVICE_DIR
#matlab -nodisplay -nosplash -r main
#singularity exec -e docker://brainlife/splitshells
singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./msa/main

#check for output files
if [ -s dwi.nii.gz ];
then
	echo 0 > finished
else
	echo "output missing"
	echo 1 > finished
	exit 1
fi





