#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=29gb,walltime=0:20:00
#PBS -N app-splitshells
#PBS -V

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
if [ ! -s dwi.nii.gz ];
then
	echo "output missing"
	exit 1
fi





